#!/bin/bash
set -euo pipefail

FLAGS="-DCLOUD_BUILD -DUSE_BLACKBOX -DUSE_DSHOT -DUSE_GPS -DUSE_GPS_PLUS_CODES -DUSE_LED_STRIP -DUSE_MAG -DUSE_OSD -DUSE_OSD_HD -DUSE_OSD_SD -DUSE_PINIO -DUSE_SERIALRX -DUSE_SERIALRX_CRSF -DUSE_TELEMETRY -DUSE_TELEMETRY_CRSF -DUSE_VTX -DUSE_CHIRP -DUSE_ALTITUDE_HOLD -DUSE_ALTHOLD_CHIRP"

make AIKONF7 EXTRA_FLAGS="$FLAGS"
