#!/bin/bash

FLIGHT_FLAGS=(
  -DCLOUD_BUILD
  -DUSE_ALTITUDE_HOLD
  -DUSE_CHIRP
  -DUSE_DSHOT
  -DUSE_GPS
  -DUSE_GPS_PLUS_CODES
  -DUSE_MAG
  -DUSE_OSD
  -DUSE_OSD_SD
  -DUSE_PINIO
  -DUSE_POSITION_HOLD
  -DUSE_SERIALRX
  -DUSE_SERIALRX_CRSF
  -DUSE_TELEMETRY
  -DUSE_TELEMETRY_CRSF
  -DUSE_VTX
  -DUSE_POSHOLD_CHIRP
)

make IFLIGHT_F722_TWING EXTRA_FLAGS="${FLIGHT_FLAGS[*]}"
